apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: gamegen-x
  labels:
    app: gamegen-x
    component: backend
    environment: production
data:
  # Project Configuration
  PROJECT_NAME: "GameGen-X"
  ENVIRONMENT: "production"
  DEBUG: "false"

  # API Configuration
  API_TITLE: "GameGen-X API"
  API_VERSION: "v1"
  API_PREFIX: "/api/v1"
  WORKERS: "4"
  CORS_ORIGINS: "https://gamegen-x.com"

  # Model Configuration
  MODEL_PATH: "/models/weights"

  # GPU Configuration for Non-NVIDIA Hardware
  GPU_MEMORY_LIMIT: "24576"  # 24GB in MB
  GPU_DRIVER_PATH: "/usr/local/lib/gpu"

  # FreeBSD Compatibility Settings
  FREEBSD_COMPATIBILITY_MODE: "true"

  # WebSocket Configuration for Real-time Video Streaming
  WS_PING_INTERVAL: "30"     # 30 seconds ping interval
  WS_PING_TIMEOUT: "10"      # 10 seconds timeout
  WS_MAX_MESSAGE_SIZE: "1048576"  # 1MB max message size